!
frr version 10.6.1_git
frr defaults traditional
hostname dev-4-2
domainname localdomain
!
ip route 10.200.40.0/24 Null0
ip route 10.200.41.0/24 Null0
!
interface eth1
 description BGP Unnumbered Peering
 ipv6 nd ra-interval 10
 no ipv6 nd suppress-ra
exit
!
interface lo
 ip address 10.2.4.2/32
exit
!
router bgp 65100
 bgp router-id 10.2.4.2
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast
 neighbor eth1 interface remote-as external
 no neighbor eth1 capability link-local
 !
 address-family ipv4 unicast
  network 10.2.4.2/32
  network 10.200.40.0/24
  network 10.200.41.0/24
  neighbor eth1 activate
  neighbor eth1 soft-reconfiguration inbound
 exit-address-family
exit
!
end